-- CreateEnum
CREATE TYPE "SeatStatus" AS ENUM ('PENDING', 'ACTIVE', 'SCHEDULED_FOR_TERMINATION', 'TERMINATED');

-- AlterTable
ALTER TABLE "Seat" ADD COLUMN     "endDate" TIMESTAMP,
ADD COLUMN     "startDate" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "status" "SeatStatus" NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE "Subscription" ALTER COLUMN "startDate" SET DEFAULT CURRENT_TIMESTAMP;
